### ISSUE TITLE
hyperlink to Gassner et al. 2004

### ISSUE THREAD

**Issue by wibeasley** [MooersLab/EasyPyMOL#2]
@bmooers, the README has a link to "Gassner et al. 2004" that I couldn't find in Google Scholar.  I suggest including it --to help readers and to help SEO.

**Comment by wibeasley** [comment]
Hyperlink added with commit d2219eb0b50580b1e0be7aa8f6c00eb5cb1f8ade

@bmooers, in the text, should the year be 2003 instead of 2004?
![image](https://cloud.githubusercontent.com/assets/1372890/11002932/64691b36-8475-11e5-82f6-6d45394bbaef.png)

**Comment by bmooers** [comment]
Hi Will,

Thank you very much for the hyperlinks and re-coding the markdown!
I accepted all of the changes.

I added a hyperlink for the Gassner et al. article to its PubMed page because the full article is not open source.
Visitors can gain access to the full article via the PubMed page if their institution has a subscription to the journal.

I am reluctant to change the github address while the article is under review.

Getting a doi and the issue of the education version sound intriguing. I defer those
matters to when I have more time. I have to get on with my NSF grant applicaiton that is due Nov. 16th.

Best regards,

Blaine

Blaine Mooers, Ph.D.
Assistant Professor
Director of the Laboratory of Biomolecular Structure and Function
Department of Biochemistry and Molecular Biology
University of Oklahoma Health Sciences Center
S.L. Young Biomedical Research Center Rm. 466

Shipping address:
975 NE 10th Street, BRC 466
Oklahoma City, OK 73104-5419

Letter address:
P.O. Box 26901, BRC 466
Oklahoma City, OK 73190

office: (405) 271-8300   lab: (405) 271-8313  fax:  (405) 271-3910
e-mail:  blaine-mooers@ouhsc.edu

Faculty webpage: http://www.oumedicine.com/department-of-biochemistry-and-molecular-biology/faculty/blaine-mooers-ph-d-

Small Angle Scattering webpage: http://www.oumedicine.com/docs/default-source/ad-biochemistry-workfiles/small-angle-scattering-links-27aug2014.html?sfvrsn=0

X-ray lab webpage: http://www.oumedicine.com/department-of-biochemistry-and-molecular-biology/department-facilities/macromolecular-crystallography-laboratory
